apiVersion: apps/v1
kind: Deployment
metadata:
  name: coraza-skipper-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        application: coraza-skipper-demo
    spec:
      containers:
      - name: coraza-skipper-demo
        image: jptosso/coraza-waf:latest
        command: ["/bin/sh", "-c"]
        args:
          - "cat << EOF > /etc/coraza-waf/routes.eskip"
          - "* -> corazaWAF('https://raw.githubusercontent.com/jptosso/coraza-waf/master/examples/skipper/default.conf') -> inlineContent(\"<body style='color: white; background-color: green;'><h1>Hello!</h1>\") -> <shunt>"
        ports:
        - containerPort: 9090