apiVersion: v1
kind: Service
metadata:
  name: coraza-skipper-demo
  labels:
    application: coraza-skipper-demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
      name: external
  selector:
    application: coraza-skipper-demo